#!/bin/bash

# ========== CONFIG ==========
LOG_FILE="$1"
PATTERN_FILE="patterns.txt"
REPORT_DIR="reports"
TIMESTAMP=$(date +"%Y%m%d_%H%M%S")
OUTPUT_FILE="$REPORT_DIR/report_${TIMESTAMP}.txt"

# Text formatting
BOLD=$(tput bold 2>/dev/null || echo "")
RESET=$(tput sgr0 2>/dev/null || echo "")

# ========== FUNCTIONS ==========

check_files() {
  if [ ! -f "$LOG_FILE" ]; then
    echo "❌ Log file '$LOG_FILE' not found!"
    exit 1
  fi
  if [ ! -f "$PATTERN_FILE" ]; then
    echo "❌ Pattern file '$PATTERN_FILE' not found!"
    exit 1
  fi
  mkdir -p "$REPORT_DIR"
}

scan_logs() {
  echo "LogShield Report - $TIMESTAMP" > "$OUTPUT_FILE"
  echo "===============================" >> "$OUTPUT_FILE"
  echo "" >> "$OUTPUT_FILE"

  echo "[📊] Suspicious IP Summary:" >> "$OUTPUT_FILE"
  grep -i -f "$PATTERN_FILE" "$LOG_FILE" | awk '{print $1}' | sort | uniq -c | sort -nr >> "$OUTPUT_FILE"

  echo "" >> "$OUTPUT_FILE"
  echo "[🔍] Matching Log Lines:" >> "$OUTPUT_FILE"
  grep -i -f "$PATTERN_FILE" "$LOG_FILE" >> "$OUTPUT_FILE"

  echo -e "${BOLD}✅ Report generated at: $OUTPUT_FILE${RESET}"
  echo ""
}

send_report_email() {
  local email="$1"
  local file="$2"

  if ! command -v termux-send-email >/dev/null 2>&1; then
    echo "❌ termux-send-email not found. Run: pkg install termux-api"
    return
  fi

  echo "[📧] Sending report to: $email"
  termux-send-email -a "$file" -s "LogShield Report - $TIMESTAMP" "$email" --body "Please find the attached suspicious activity report generated by LogShield."
  echo "[✅] Email sent!"
}

# ========== MAIN ==========

check_files
echo "✅ Log File: $LOG_FILE"
echo "✅ Pattern File: $PATTERN_FILE"

scan_logs

# Show report preview
echo "---- Report Preview ----"
head -20 "$OUTPUT_FILE"
echo "------------------------"

# Ask for email
echo -e "\n[📨] Enter your email address to receive the report (or press Enter to skip):"
read user_email

if [ -n "$user_email" ]; then
  send_report_email "$user_email" "$OUTPUT_FILE"
else
  echo "[ℹ️] Skipping email."
fi
